### ISSUE TITLE
Out of the box superbuild fails

### ISSUE THREAD

**Issue by zachmullen** [InsightSoftwareConsortium/covalic#1]
When the option `Covalic_USE_ITKV4` is set to `OFF` (which is the default), the project attempts to superbuild against a tag that cannot be found, causing the clone step to fail. The tag in question:

```
GIT_REPOSITORY "${GIT_PROTOCOL}://github.com/Slicer/ITK.git"
GIT_TAG "origin/slicer-4.0"
```

**Comment by prastawa** [comment]
Fixed in latest version with ITK v4 as default.
